name: plotbot_micromamba
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scipy
    - cdflib
    - beautifulsoup4
    - requests
    - python-dateutil
    - pytest
    - termcolor
    - ipykernel
    - ipywidgets
    - jupyter
    - notebook

